apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnflow-ingress
  namespace: learnflow
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnflow-frontend
                port:
                  number: 80
          # API routes
          - path: /api/triage
            pathType: Prefix
            backend:
              service:
                name: triage-service
                port:
                  number: 80
          - path: /api/concepts
            pathType: Prefix
            backend:
              service:
                name: concepts-service
                port:
                  number: 80
          - path: /api/exercises
            pathType: Prefix
            backend:
              service:
                name: exercise-service
                port:
                  number: 80
          - path: /api/execute
            pathType: Prefix
            backend:
              service:
                name: code-execution-service
                port:
                  number: 80
