apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: learnflow
  annotations:
    dapr.io/component-init-timeout: "120s"
spec:
  type: state.postgresql
  version: v1
  initTimeout: 120s
  ignoreErrors: true
  metadata:
    - name: connectionString
      secretKeyRef:
        name: postgres-credentials
        key: DATABASE_URL
    - name: tablePrefix
      value: ""
    - name: metadataTableName
      value: "dapr_metadata"
    - name: tableName
      value: "state"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: learnflow
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "learnflow-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
    - name: authType
      value: "none"
    - name: consumerGroup
      value: "learnflow-group"
